name: SimplePortals
main: falkirks\simpleportals\SimplePortals
author: Falkirks
version: 0.0.4
api: [1.13.0]
depend: ["SimpleWarp"]
permissions:
  simpleportals:
    default: op
    children:
      simpleportals.create:
        default: op
        description: Create a new portal
      simpleportals.use:
        default: true
        description: Use existing portals
